/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Record } from "./Record";
import { RecordCountArgs } from "./RecordCountArgs";
import { RecordFindManyArgs } from "./RecordFindManyArgs";
import { RecordFindUniqueArgs } from "./RecordFindUniqueArgs";
import { CreateRecordArgs } from "./CreateRecordArgs";
import { UpdateRecordArgs } from "./UpdateRecordArgs";
import { DeleteRecordArgs } from "./DeleteRecordArgs";
import { User } from "../../user/base/User";
import { RecordService } from "../record.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Record)
export class RecordResolverBase {
  constructor(
    protected readonly service: RecordService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Record",
    action: "read",
    possession: "any",
  })
  async _recordsMeta(
    @graphql.Args() args: RecordCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Record])
  @nestAccessControl.UseRoles({
    resource: "Record",
    action: "read",
    possession: "any",
  })
  async records(@graphql.Args() args: RecordFindManyArgs): Promise<Record[]> {
    return this.service.records(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Record, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Record",
    action: "read",
    possession: "own",
  })
  async record(
    @graphql.Args() args: RecordFindUniqueArgs
  ): Promise<Record | null> {
    const result = await this.service.record(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Record)
  @nestAccessControl.UseRoles({
    resource: "Record",
    action: "create",
    possession: "any",
  })
  async createRecord(@graphql.Args() args: CreateRecordArgs): Promise<Record> {
    return await this.service.createRecord({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Record)
  @nestAccessControl.UseRoles({
    resource: "Record",
    action: "update",
    possession: "any",
  })
  async updateRecord(
    @graphql.Args() args: UpdateRecordArgs
  ): Promise<Record | null> {
    try {
      return await this.service.updateRecord({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Record)
  @nestAccessControl.UseRoles({
    resource: "Record",
    action: "delete",
    possession: "any",
  })
  async deleteRecord(
    @graphql.Args() args: DeleteRecordArgs
  ): Promise<Record | null> {
    try {
      return await this.service.deleteRecord(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(@graphql.Parent() parent: Record): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
