/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  SudokuGame as PrismaSudokuGame,
  User as PrismaUser,
} from "@prisma/client";

export class SudokuGameServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.SudokuGameCountArgs, "select">
  ): Promise<number> {
    return this.prisma.sudokuGame.count(args);
  }

  async sudokuGames(
    args: Prisma.SudokuGameFindManyArgs
  ): Promise<PrismaSudokuGame[]> {
    return this.prisma.sudokuGame.findMany(args);
  }
  async sudokuGame(
    args: Prisma.SudokuGameFindUniqueArgs
  ): Promise<PrismaSudokuGame | null> {
    return this.prisma.sudokuGame.findUnique(args);
  }
  async createSudokuGame(
    args: Prisma.SudokuGameCreateArgs
  ): Promise<PrismaSudokuGame> {
    return this.prisma.sudokuGame.create(args);
  }
  async updateSudokuGame(
    args: Prisma.SudokuGameUpdateArgs
  ): Promise<PrismaSudokuGame> {
    return this.prisma.sudokuGame.update(args);
  }
  async deleteSudokuGame(
    args: Prisma.SudokuGameDeleteArgs
  ): Promise<PrismaSudokuGame> {
    return this.prisma.sudokuGame.delete(args);
  }

  async getUser(parentId: string): Promise<PrismaUser | null> {
    return this.prisma.sudokuGame
      .findUnique({
        where: { id: parentId },
      })
      .user();
  }
}
