/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SudokuGameService } from "../sudokuGame.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SudokuGameCreateInput } from "./SudokuGameCreateInput";
import { SudokuGame } from "./SudokuGame";
import { SudokuGameFindManyArgs } from "./SudokuGameFindManyArgs";
import { SudokuGameWhereUniqueInput } from "./SudokuGameWhereUniqueInput";
import { SudokuGameUpdateInput } from "./SudokuGameUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SudokuGameControllerBase {
  constructor(
    protected readonly service: SudokuGameService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SudokuGame })
  @nestAccessControl.UseRoles({
    resource: "SudokuGame",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createSudokuGame(
    @common.Body() data: SudokuGameCreateInput
  ): Promise<SudokuGame> {
    return await this.service.createSudokuGame({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        board: true,
        createdAt: true,
        id: true,
        solvedBoard: true,
        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [SudokuGame] })
  @ApiNestedQuery(SudokuGameFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "SudokuGame",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async sudokuGames(@common.Req() request: Request): Promise<SudokuGame[]> {
    const args = plainToClass(SudokuGameFindManyArgs, request.query);
    return this.service.sudokuGames({
      ...args,
      select: {
        board: true,
        createdAt: true,
        id: true,
        solvedBoard: true,
        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SudokuGame })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SudokuGame",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async sudokuGame(
    @common.Param() params: SudokuGameWhereUniqueInput
  ): Promise<SudokuGame | null> {
    const result = await this.service.sudokuGame({
      where: params,
      select: {
        board: true,
        createdAt: true,
        id: true,
        solvedBoard: true,
        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SudokuGame })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SudokuGame",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateSudokuGame(
    @common.Param() params: SudokuGameWhereUniqueInput,
    @common.Body() data: SudokuGameUpdateInput
  ): Promise<SudokuGame | null> {
    try {
      return await this.service.updateSudokuGame({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          board: true,
          createdAt: true,
          id: true,
          solvedBoard: true,
          status: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SudokuGame })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SudokuGame",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteSudokuGame(
    @common.Param() params: SudokuGameWhereUniqueInput
  ): Promise<SudokuGame | null> {
    try {
      return await this.service.deleteSudokuGame({
        where: params,
        select: {
          board: true,
          createdAt: true,
          id: true,
          solvedBoard: true,
          status: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
